// <auto-generated />
using Challenge_3_Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Challenge_3_Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190919123909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Challenge_3_Web.Models.RowData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Activity");

                    b.Property<int>("GroupNumber");

                    b.Property<int>("Pred");

                    b.Property<double>("xAco");

                    b.Property<double>("xGyro");

                    b.Property<double>("xLinAco");

                    b.Property<double>("xMag");

                    b.Property<double>("yAco");

                    b.Property<double>("yGyro");

                    b.Property<double>("yLinAco");

                    b.Property<double>("yMag");

                    b.Property<double>("zAco");

                    b.Property<double>("zGyro");

                    b.Property<double>("zLinAco");

                    b.Property<double>("zMag");

                    b.HasKey("Id");

                    b.ToTable("RowData");
                });
#pragma warning restore 612, 618
        }
    }
}
